language: node_js
node_js:
  - 8
after_success:
  - npm run codecov
  - npm run storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: .site
  on:
    branch: master
