language: node_js
node_js:
  - 10
script: npm test -- --coverage --runInBand
after_success:
  - npm run codecov
before_install:
  - npm i -g npm@6.4.1
before_deploy:
  - cd docs
  - npm install
  - npm run build
  - touch out/.nojekyll
  - cd ..
  - npm run storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs/out
  on:
    branch: master
