# This workflow will do a clean install of node dependencies before building the static Storybook and docsite
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Static Docsite and Storybook

on:
  push:
    branches: [master]

jobs:
  docsite_storybook_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: NPM Install
        working-directory: docs
        run: npm install

      - name: Build docsite
        working-directory: docs
        env:
          NODE_ENV: production
        run: |
          npm run build
          touch out/.nojekyll

      - name: Build static Storybook
        working-directory: ./
        run: |
          npm install
          npm run storybook

      - name: Push build directory to GitHub Pages branch
        uses: s0/git-publish-subdir-action@v2.3.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs/out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
